compute_environment: LOCAL_MACHINE
deepspeed_config: 
  deepspeed_config_file: ./configs/zero2_config_local.json
  zero3_init_flag: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 8
main_process_port: 8899
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
mixed_precision: fp16
